name: Build Package for all Platforms

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        triple:
          - "arm64-apple-ios"
          - "x86_64-apple-macosx"
          - "arm64-apple-watchos"
          - "arm64-apple-ios-macabi"
          - "arm64-apple-visionos"
          - "arm64-apple-tvos"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Swift 6
        run: |
          brew install swift
          swift --version

      - name: Build Swift Package
        run: |
          swift build --triple ${{ matrix.triple }}
